# Generated by Django 4.1.5 on 2023-04-11 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='wordcloud',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
