# Generated by Django 4.1.5 on 2023-04-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_text_wordcloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='wordcloud',
        ),
    ]
