# Generated by Django 4.1.5 on 2023-04-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_document_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_title',
        ),
    ]
