# Generated by Django 4.1.5 on 2023-04-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_text_graph_remove_text_wordcloud_text_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='id',
        ),
        migrations.AddField(
            model_name='text',
            name='graph',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='text',
            name='wordcloud',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
