# Generated by Django 4.1.5 on 2023-04-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_text_id_text_graph_text_wordcloud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='text',
            name='wordcloud',
        ),
    ]
