# Generated by Django 4.1.5 on 2023-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_text_graph_remove_text_wordcloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.CharField(max_length=10000000),
        ),
    ]
